trictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

ignore-paths:
  - .venv

ignore-patterns:
  - (^|/)tests/__init__\.py$

pep8:
  full: true
  options:
    max-line-length: 120

pep257:
  disable:
    - D203
    - D212
    - D407
    - D413

pylint:
  options:
    max-line-length: 120

vulture:
  run: true

mypy:
  run: true
